### ISSUE TITLE
Band pass filtering not working at lower values

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#102]
Javier Pacheco reports problem filtering between 0.0125 and 0.1.  Confirmed by Jeremy.  Works at higher at higher values.  Seems to go back to at least 2.6.2. 

![clipboard](https://cloud.githubusercontent.com/assets/25251719/26592174/d1f7ee50-4514-11e7-9516-bf645a645f69.png)

**Comment by dnorgaard-usgs** [comment]
Similar results obtained from Matlab.  Maybe a non-issue?

**Comment by tparker-usgs** [comment]
Matt suggests using a low-order filter with zero phase shift. This seems to produce reasonable results, but I haven't validated it.
