### ISSUE TITLE
Map settings - allow all station decorations to be removed

### ISSUE THREAD

**Issue by lantolik-usgs** [usgs/swarm#124]
**current -** 
at startup, with no data source selected - station locations and decorations are not displayed.

with a data source selected - current map settings allow for none, some, all, which is referring to station names.   the green icon displaying station locations is always present.  

with a data source deselected - station locations and decorations don't change

**proposed -** 
regardless of whether a data source is selected or not, have buttons refer to the green icon.  have an additional checkbox (on by default?) that refers to icon labels (station codes) being displayed.

therefore, with none selected, nothing will be shown. 

the goal - an EQ map similar to NEIC earthquakes page, that only shows EQ locations.

**Comment by lantolik-usgs** [comment]
alternatively, have all station decorations removed when de-selecting the data source.

although - it is the action of double clicking a data source that initiates station decorations displaying - a single click is not sufficient.    therefore, a single click to deselect may not be sufficient to remove station decorations, currently.

**Comment by dnorgaard-usgs** [comment]
feature will go into version 2.8.6 when released.  go to map options and check 'Hide Stations':

![image](https://user-images.githubusercontent.com/25251719/43109662-bc7e4aec-8e9c-11e8-9ac1-154ed1915aa6.png)
