### ISSUE TITLE
FDSN WS data chooser does not work with virtual networks

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#138]
Example: http://service.iris.edu/irisws/virtualnetwork/1/query

Brian:  It only lets you chose from a static list of network codes there.  If I go into the Swarm.config and enter the virtual network in place of a network code, Swarm doesn't know what to do with it.  I tried using the IRIS web services URL as well without success: https://service.iris.edu/irisws/virtualnetwork/1/

**Comment by dnorgaard-usgs** [comment]
Brian:  I did try some others with no luck.  List is here: http://service.iris.edu/irisws/virtualnetwork/1/codes  Thanks for looking.  This isn't a priority, just a curiosity since it would make it simpler to monitor IRIS data for our geographic region from various networks at once.

**Comment by dnorgaard-usgs** [comment]
Failing with following error when trying to getNetworkList in WebServicesPanel:


__Error in connection with url: http://service.iris.edu/irisws/virtualnetwork/1/query?net=*&level=network&format=xml&includeavailability=false
Error 400: doIrisProcessing - No type defined or unknown query parameter: includeavailability

Request:
http://service.iris.edu/irisws/virtualnetwork/1/query?net=*&level=network&format=xml&includeavailability=false

Request Submitted:
2017/09/27 16:37:35 UTC

Service version:
Service: irisws-virtualnetwork  version: 1.0.13__

No error is logged to console or displayed to user.

**Comment by dnorgaard-usgs** [comment]
It appears http://service.iris.edu/irisws/virtualnetwork/1/codes with no parameters should be used to fetch network codes. See http://service.iris.edu/irisws/virtualnetwork/1/.  However, doing so still results in below error in seisFile library (StaxUtil.expectStartElement):

![image](https://user-images.githubusercontent.com/25251719/30927583-c9fdf304-a36d-11e7-91bb-8f5a3dbdbf48.png)

Given the difference in the results from http://service.iris.edu/irisws/virtualnetwork/1/codes vs http://service.iris.edu/fdsnws/station/1/query, IRIS virtual networks probably need to be handled differently.

I've opened a ticket with seisFile to inquire about status/plans to support IRIS virtual network (see https://github.com/crotwell/seisFile/issues/9).  As of the moment, it does not appear supported per their README (https://github.com/crotwell/seisFile).  It is also not listed under data centers supporting FDSN web services.

**Comment by tparker-usgs** [comment]
The interface is goofy, but it seems to work for me. I'm able to click the new data source button, edit the network field to contain _HAWAII, click the OK button and all seems to work as expected. Including persistence across launches.

In my Swarm.config I see:
```
server=hawaii;wsc:_HAWAII||||3600|1000|http://service.iris.edu/fdsnws/dataselect/1/query|http://service.iris.edu/fdsnws/station/1/query
```

@dnorgaard-usgs Is the issue only that the selection list is not prepopulated with virtual networks?

**Comment by dnorgaard-usgs** [comment]
I haven't tried the config route, but in the FDSN WS panel you cannot populate the network list using the virtual network station url.

**Comment by tparker-usgs** [comment]
You cannot populate the network list, but the combo box is editable. It's happy with just a network code.

**Comment by dnorgaard-usgs** [comment]
Looks like it's working for Brian as well.

**Comment by dnorgaard-usgs** [comment]
If there ever becomes a need to parse IRIS virtual network URL in future, support for it should be in next seisFile release.

On Wed, Sep 27, 2017 at 1:38 PM, Philip Crotwell <notifications@github.com> wrote:
Virtual Network is in github, but not in the 1.7.4 release. You can look here:
https://github.com/crotwell/seisFile/tree/master/src/main/java/edu/sc/seis/seisFile/fdsnws/virtualnet

I do not know when I will be able to push out next release, will see if I can find time to do soon.
