### ISSUE TITLE
Add new data source (Enhancement, not bug)

### ISSUE THREAD

**Issue by osop-raspishake** [usgs/swarm#141]
New data source tab: "OSOP Wave Server" (turns SeisComP SDS into a wave server)

Same code as WWS but on port 16032 by default.

**Comment by osop-raspishake** [comment]
Sorry, Jargon. SDS = the SeisComP Data Structure or the miniSEED files on disk.

**Comment by tparker-usgs** [comment]
We're reluctant to add another option to the current data source pane if it doesn't affect functionality. However, it may be possible to provide some annotation in the GUI to note common default port number of known servers.

**Comment by osop-raspishake** [comment]
Bummer :)
Perhaps "Winston Wave Server / OWS" or "WWS/ OWS"

The annotations could be:

"
Use this data source to connect to a Winston Wave Server (WWS) or OSOP Wave Server (OWS).
The default port for the OWS is 16032.
"

Then, 

"
Port: 16022 Winston default: 16022, OWS default: 16032
"

**Comment by dnorgaard-usgs** [comment]
How's this?

![image](https://user-images.githubusercontent.com/25251719/43107470-00c7549c-8e92-11e8-87b2-887acf019a6f.png)

Spelling out OSOP Wave Server would require a second line.  Looked cleaner if I could get the annotation on one line.

**Comment by tparker-usgs** [comment]
The text should make the distinction between protocol and application more clear. We wouldn't want to list every program which supports the Winston Wave Server protocol in the box. Maybe something more like:

> Use this data source to connect to servers which support the Winston Wave Server protocol (e.g. WWS or OWS)

I would leave just the one 16022 default. That's the default used by the WWS protocol.

**Comment by dnorgaard-usgs** [comment]
I'm inclined to agree with Tom on not wanting to list all programs that support the protocol.  Reverting, with minor change, to:

![image](https://user-images.githubusercontent.com/25251719/43108817-94b30c54-8e98-11e8-9323-bdcd208c8c5e.png)

**Comment by dnorgaard-usgs** [comment]
Sorry Branden!

**Comment by osop-raspishake** [comment]
Thank you Diana and Tom:

Good morning.

Technically, OWS is a completely separate protocol. We just spoof the WWS protocol when data requests are received from Swarm in order to play well with Swarm/ make things transparent to Swarm. 7 years ago when the Swarm code was not in github, it was just easier to it this way. Actually, I do not think we thought it was even possible to create a branch of Swarm that spoke directly to OWS and then send a merge request. 

How OWS is different from WWS?: It gets its data from both SeedLink and the SeisComP Data Structure (SDS) miniSEED database. There is mysql waveform database involved. 

I originally requested that "OSOP Wave Server (OWS)" appear in a separate tab just to make it easier for users to find it and configure things, mostly first time users. At the moment, users still get confused because there is no mention of OSOP Wave Server, only WWS. But it is a minor point, really. 

Thank you guys for your support and for all of the recent enhancements to Swarm!


Yours, Branden
