### ISSUE TITLE
streaming wave fails on loss of data

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/swarm#142]
Wave view windows on the map display will not recover if the instrument temporarily stops sending data.

**Comment by dnorgaard-usgs** [comment]
Another interested party:

On Fri, Jul 20, 2018 at 12:14 AM, Elmar  wrote:
Hi Diana,

thanks for your email and for taking care of the bug. Unfortunately, there is no error message in the cmd window when this happens. I attached a screenshot showing also the command window. I use a setup of three data loggers locally connected to earthworm via slink2ew or import_generic. Like this I can easily turn on/off the modules for testing. Unfortunately, it you cannot connect to this local setup.

Please let me know if you could fix that bug, I will then test the new version again.
![swarm_testing](https://user-images.githubusercontent.com/25251719/43011844-7d8d4716-8bf9-11e8-8971-bb015cf2a912.jpg)
 
Cheers,

Elmar
 
On Thu, Jul 19, 2018 at 2:40 AM, Elmar  wrote:

Hi Tom,
 
I am currently testing version 2.8.5 of Swarm. Unfortunately, it seems that the already known bug “streaming wave fails on loss of data” (#142 opened on 28 Sep 2017 by tparker-usgs, Wave view windows on the map display will not recover if the instrument temporarily stops sending data.) still exists. I attached a snapshot of versions 2.7.4 and 2.8.5 running in parallel.

Could you already estimate when it is possible to fix this bug?

 Thanks and regards,

Elmar

**Comment by dnorgaard-usgs** [comment]
Received confirmation from Elmar that this bug is fixed for him.
