### ISSUE TITLE
camera icon freeze

### ISSUE THREAD

**Issue by jpesicek** [usgs/swarm#153]
Stephanie and Jay report that use of the camera icon to save figures often causes swarm to freeze. No other details at the moment

**Comment by dnorgaard-usgs** [comment]
Will give it a few weeks to see if this issue crops up in latest version of Swarm.  If not will close.

On Tue, Nov 7, 2017 at 2:13 PM, Stephanie wrote:

The freezing problem seems to be gone in 2.8.1 for me. Thanks!

Stephanie

On Mon, Nov 6, 2017 at 11:17 AM, Norgaard, Diana <dnorgaard@usgs.gov> wrote:
https://github.com/usgs/swarm/issues/153

Hi Stephanie/Jay,

Are you still seeing camera freezing issue in Swarm?  Can you please let me know if you continue to see it in 2.8.1?  Also, please let me know which window it is in when it happens (e.g. clipboard, helicorder, etc.) and whether there are any console errors.

thanks,
Diana

**Comment by dnorgaard-usgs** [comment]
No one has reported further issues on this after requesting further info if it happens again.  Closing.  Will reopen if problem persists.
