### ISSUE TITLE
quakeml namespace

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/swarm#170]
Paolo reports:

    I found an issue in vers. swarm 2.7 and 2.8, and I hope you can point me to the right person to report this.
 
    I am trying to parse a quakeml file exported from swarm to extract picks time values.
 
    I use either obspy or the lxml   etree.parser. However the quakeml file generated by swarm seems to be missing a namespace:  {'q': 'http://quakeml.org/xmlns/quakeml/1.2'}
 
    If I add to the .quakeml file the namespace and save the file, then it works.

**Comment by dnorgaard-usgs** [comment]
added missing xmlns attributes to exported quakeml files
