### ISSUE TITLE
HYPO71 implementation does not support 5 char station names

### ISSUE THREAD

**Issue by seismopaul** [usgs/swarm#172]
**For the Event Dialog:**

The HYPO71 conversion to Java should support the SEED convention. Currently, the 5 char station names are truncated and no stations are found if they have more than 4 chars...even though picks can be made with 5 char station names.

Please note that SEED naming convention (which is supported by WINSTON, SWARM, PENSIVE) for station names allows a maximum of 5 characters. 

This was discovered using Swarm 2.8.2 on a MAC OS X running Java 1.7.0_45.

**Comment by dnorgaard-usgs** [comment]
I think I found the issue, but am having a hard time finding data source with 5 char station names to test with.  Can you point me to one, or test the fix if I send you an update of Swarm?

**Comment by seismopaul** [comment]
I can absolutely test this with a setup that I have here where 5 out of 6 stations have 5-char names. Thanks for the quick turn-around on this fix.

**Comment by dnorgaard-usgs** [comment]
[swarm-2.8.3-SNAPSHOT-bin.zip](https://github.com/usgs/swarm/files/1519472/swarm-2.8.3-SNAPSHOT-bin.zip)

**Comment by dnorgaard-usgs** [comment]
[swarm-2.8.3-SNAPSHOT-bin.zip](https://github.com/usgs/swarm/files/1522785/swarm-2.8.3-SNAPSHOT-bin.zip)

Updated 2.8.3 snapshot attached.

I corrected the output format to support 5 char station, but it is still not locating. I'm also not seeing any place where the stations are truncated to 4 chars.  Stepping through code station names remain 5 chars. Still getting the 'INSUFFICIENT DATA' message.  The code is quite messy (straight conversion from Fortran w/o any cleanup) so it could be I missed something, but I also wonder if it could be something else. I'll keep looking into it though.

Btw, no idea on your pick export issue, but if you now get a 'QuakeML file not saved' message, it means it's not picking up a filename to save to.

**Comment by dnorgaard-usgs** [comment]
I believe this issue is fixed.  The problem we were seeing had more to do with the data coming from out of network.  The Hypo71 KSING option was also added to address the in/out network issue. Changes will go into 2.8.3 but no eta yet on release date.
