### ISSUE TITLE
The Butterworth Filter Dialog doesn't allow more than 1 decimal precision for corner 

### ISSUE THREAD

**Issue by seismopaul** [usgs/swarm#173]
When putting a low frequency value of 0.01 the dialog converts this to 0.0.

It only currently allows one decimal point of precision. This allows the low-pass butterworth to only go as low as 0.1 Hertz (10 seconds period), but often there are broad-band data that need filtering below this value. Please allow at least 2 decimal places. Thank you.

**Comment by dnorgaard-usgs** [comment]
fixed.  will go into 2.8.3 but no eta yet on release date.
