### ISSUE TITLE
auto-rescale clipboard feature request

### ISSUE THREAD

**Issue by jpesicek** [usgs/swarm#178]
Would be nice to have a button to auto-rescale all the waveforms in the clipboard.  When you have many in the clipboard, and then click to a new smaller signal, the waveforms keep their previous scaling. Would be nice to press one button to auto rescale all at once in this case. muchas gracias

**Comment by dnorgaard-usgs** [comment]
User can rescale multiple waveforms by selecting all the waveforms he wants to rescale before hitting 'r'.  User can use Ctrl or Shift to select multiple waveforms.
