### ISSUE TITLE
fixed scaling bug

### ISSUE THREAD

**Issue by osop-raspishake** [usgs/swarm#183]
For details, please see: https://groups.google.com/forum/#!topic/raspberryshake/0s_HVRDXF4E

**Comment by dnorgaard-usgs** [comment]
Hi.  Can you please elaborate on the issue?  I was not able to reproduce either of the two issues mentioned in the thread.

**Comment by osop-raspishake** [comment]
I have emailed the Raspberry Shaker who first reported it to see if this issue is still outstanding. I am awaiting his reply (though the thread has already be pirated): https://groups.google.com/forum/#!topic/raspberryshake/0s_HVRDXF4E. Let's see if John replies. 


Yours, Branden

**Comment by dnorgaard-usgs** [comment]
Any update?

**Comment by osop-raspishake** [comment]
None. I would say we can close this ticket. Thanks!
