### ISSUE TITLE
SWARM S-P calculation should allow adjusting Vp/Vs ratio value

### ISSUE THREAD

**Issue by seismopaul** [usgs/swarm#185]
This is an enhancement request: I see that the P velocity is settable in swarm, but the ratio to obtain the S velocity is not (well it isn't on the **File->Options** dialog that pops up. It would be nice to be able to set the Vp/Vs value in case the value is non-standard for a given region.

**Comment by dnorgaard-usgs** [comment]
This will go into version 2.8.4.
