### ISSUE TITLE
Enhancement request: Spectrogram Options, set Max. frequency based on sample rate

### ISSUE THREAD

**Issue by osop-raspishake** [usgs/swarm#195]
Currently, the default is 25.0 Hz. I suggest that if the sample rate is 100 sps, this should default to 50.0 Hz. 

See: Wave settings >> Spectrogram Options >> Max. frequency

Branden

**Comment by dnorgaard-usgs** [comment]
Hi Branden.  The wave settings dialog is designed to take defaults from WaveDefaults.config. I'm not sure there's a good way to set the default dynamically without conflicting with this feature. If most of your data sources use a sample rate of 100 sps, you can change the default there.

**Comment by osop-raspishake** [comment]
Good solution. Thank you. When I set to 50 as default max, the spectrogram for 50 sps channels is automatically shown from 0 to 25 and not 0 to 50. Nice!

Closed.
