### ISSUE TITLE
Clipboard button doesn't work

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/swarm#198]
The clipboard cannot be opened by clicking the button at the bottom of the data chooser.

**Comment by dnorgaard-usgs** [comment]
Actually, now I see the difference.  In some cases you get an empty wave panel and in others there is 'No wave data' when you should probably get an empty panel.  I'll dig around a bit more.

**Comment by tparker-usgs** [comment]
That makes sense. The original report came from a use who expected the clipboard to become visible when the button was clicked, even when no data source was selected. That might be a good idea, but it is different than how the other buttons work.

I'm closing this ticket.
