### ISSUE TITLE
Better maps

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#208]
Jeremy suggested a better base map would be nice.

**Comment by virusdunil** [comment]
Better or more sources with some layers/legends ect.

**Comment by dnorgaard-usgs** [comment]
Looked into Google Maps a bit since a lot of people mention it.  It seems it would be cost prohibitive since static maps can only return images up to 640x640 pixels unless we have a premium plan.  Even if there were no size restrictions, we'd probably need to have individual users generate their own API key and input it, as there's some daily quota on free usage limit.  It does not seem to be a practical option.

**Comment by dnorgaard-usgs** [comment]
The default USGS maps seem to be the best for US locations.  If there are other WMS services out there that provide better maps for international locations, we might incorporate it into the drop down for WMS map option.

**Comment by dnorgaard-usgs** [comment]
As for ESRI, far as I can tell, to use their maps in Java applications, you have to have access to ArcGIS Server.

**Comment by dnorgaard-usgs** [comment]
I've not found any WMS sources, and MapPacks support detailed maps where needed.
