### ISSUE TITLE
Set helicorder scale in config file?

### ISSUE THREAD

**Issue by iannesbitt** [usgs/swarm#229]
I've searched the docs for this functionality but couldn't find it. I'm working on a Swarm setup that would serve as an unattended kiosk in a university building lobby, and it would be impractical to have to go into the GUI to adjust the helicorder scale every time the kiosk computer boots. I think kiosk mode users would find it very helpful to be able to set the helicorder scaling via a numeric value in one of the config files.

**Comment by dnorgaard-usgs** [comment]
Hi.  Have you tried unchecking Auto-scale in the helicorder view settings, and setting the One bar range?  There is more info on this in the documentation under section 4.4.1.  You can open the helicorders you want to display in Kiosk mode, change the settings, and save as a layout.  Next time you open Swarm, open the saved layout and then go into Kiosk mode (F11 to toggle in/out).

**Comment by dnorgaard-usgs** [comment]
At the moment the Swarm config does not store default layout to use.  I opened a new ticket #230 for this and will close this one.

**Comment by iannesbitt** [comment]
Thank you, I appreciate it.
