### ISSUE TITLE
SwarmMetadata.config

### ISSUE THREAD

**Issue by comoglu** [usgs/swarm#239]
The following lines are from my SwarmMetada.config
ARMA BHZ AU= Unit: nm/s;Longitude: 151.628; Latitude: -30.4198; Group:ANSN 
ARMA BHZ AU= Unit: nm/s;Longitude: 151.628; Latitude: -30.4198; Group:ANSN 
ARMA BHZ AU= Unit: nm/s;Longitude: 151.628; Latitude: -30.4198; Group:ANSN 

My question is How can I specify the LocationCode with this context?

**Comment by dnorgaard-usgs** [comment]
The location code should be part of the channel string, e.g.:

ARMA BHZ AU 01= Unit: nm/s;Longitude: 151.628; Latitude: -30.4198; Group:ANSN

**Comment by comoglu** [comment]
Thanks for that. I used all other possibilities but this.
