### ISSUE TITLE
include picks in sac header on export

### ISSUE THREAD

**Issue by jpesicek** [usgs/swarm#249]
picks made in the clipboard are not saved to the sac headers on export, but should be

**Comment by dnorgaard-usgs** [comment]
https://ds.iris.edu/files/sac-manual/manual/file_format.html

**Comment by dnorgaard-usgs** [comment]
P -> A/KA
S -> T0/KT0
C1,C2-> T1/KT1, T2,KT2

**Comment by dnorgaard-usgs** [comment]
in 2.8.10
