### ISSUE TITLE
Multiple important things... suggestions/ideas/issue fixes

### ISSUE THREAD

**Issue by washingtonmagma** [usgs/swarm#251]
My name is Ben Ferraiuolo and I have been using SWARM for about 6 months now. It is an absolutely wonderful program but I believe there are a few issues or new options that definitely should be added if worth it. I am new to github and only signed up to post these suggestions/ideas/issue fixes.

I contacted Diana Norgaard about this and she suggested I come over here to post any suggestions/ideas/issue fixes. I do have a few:

1. Is there any way you can completely separate the spectra settings from the spectrogram settings? Currently, if "log power" is unchecked and you switch to the spectrogram window, it renders it virtually unusable. A few times here and there and it is not that big of a deal. But when doing in-depth analysis of multiple events within an earthquake swarm, it gets tedious having to go back into the settings every single time I want to switch from Spectra to Spectrogram. This must indicate that the spectra and spectrogram settings are connected in some way, although they shouldn't be at all. This is even proven in the Min/Max frequency scale for the spectrogram settings. If you change the min/max scale, it will also change the scale of the spectra window. So, is there any way to completely separate the Spectra settings and the Spectrogram settings so they no longer affect each other? This important fix, if implemented, must come along with #2:

2. The Spectra settings now will have a min/max frequency box. If #1 is implemented and the Spectra settings and the Spectrogram settings are completely separated, then #2 here will need to be implemented as well, though not as needed as #1 I believe. However I think it is paramount that #1 and #2 are implemented in some way.

3. Now I want to talk about filters. First off, when adding a band pass, low pass, or high pass filter, can you please add a check-box in the helicorder settings that says "Also filter helicorder"? Currently, you can only filter the specific analysis windows, not the helicorder on the clipboard. However this would allow you to apply the filter to the helicorder you are viewing. For example, say you just opened a HHZ or BHZ channel and the microseisms are quite strong, almost blocking smaller events, and you just went into wave settings to set a 1Hz high pass filter. Well you can remove those pesky background microseisms, not only on the separate plot windows, but also on the helicorder just by adding this one option. Of course it isn't that crazy of a need, but it would definitely be very helpful especially when analyzing earthquake swarms from broadband data (which I analyze A LOT).

4. This is for the Save Helicorder Image option: If you currently have a filter enabled in the wave settings, you should be able to save that helicorder screen capture with that filter applied. It is somewhat similar to adding the check box to the helicorder settings I mentioned in #3. It would be awesome to see a check box in the Save Helicorder Screen Capture tab that says something like, "Apply wave filter to image". The check box would most likely appear right under the current "Include Channel" check box. 

---The next idea is a big one and I highly doubt it would ever be implemented but it is good to dream! However, if it were implemented, it would be extremely helpful in my opinion (especially to the research I do). Last but certainly not least is #5:

5. Now I know there is currently a screen shot button for saving helicorder images on the clipboard, called Save Helicorder Image, but I noticed there is nothing for generating plot images for those 3 analysis windows that are commonly used (seismogram/waveform, spectrogram, spectra). Since there is no button or option to generate 1, 2, or even 3-plot images, I have to generate those plots by taking a screen shot using my computer and then copying and pasting each of them onto Paint or Photoshop. It can get a little time consuming when dealing with multiple events. I have an idea for a new button to add to the clipboard that I am sure many people will be delighted to use. At least I would be grateful to see it implemented. My idea is as follows:

On the helicorder clipboard, next to the camera icon which is the helicorder screenshot option, there would be another one that looks similar, right next to it, called “plot generator” or something like that. It would be similar to the helicorder screenshot option but with a few awesome differences:

First you must select an area on the clipboard using either the seismogram or spectrogram analysis windows (or the spectra if you really want). Whatever time period is within that window, will be the time period for all plots on the image generated using the “plot generator” option. 

Once the “plot generator” button is clicked, it will open a tab looking similar to the “save helicorder screen capture” tab. There would be image properties allowing you to change the height and width of the end result, the type of image (.png, etc…), and will also have 3 check boxes that say “include channel”, “include date”, and "Include filter". Next there will be an option that allows you to select which plots you would like to generate for the image (i.e. seismogram, spectrogram, etc…). You can select one, two, or select all three. If I select all three (seismogram/spectrogram/spectra) then when the image is saved the seismogram plot would be on the top of the image, the spectrogram in the middle, and the spectal plot at the bottom (or whatever order is best, but that seems to be the best order). The channel and date would be labeled at the bottom of the image, oreferrably to the left so we can add additional captions via Paint or Photoshop if needed. The “plot generator” would be completely in tune with any options set prior to pressing the icon.

Now since the two spectra options (in wave settings) directly affect the spectrogram plots (which I believe is a glitch, see #1 and #2 on this page) those two aspects of analysis settings need to be separated first before this plot generator is added. That is just in case someone wants “log power” unchecked for the spectra plot while generating seismogram/spectrogram/spectra 3-plot images (since having that option unchecked in spectra makes the spectrogram plots basically unusable).

Conclusion: Well I hope you enjoyed my thoughts and ideas. I think some of these ideas would really make this program even better than what it is now (although it is pretty dang good right now). I hope you all have a great day and please feel free to send me an email at any time at washingtonmagma@yahoo.com.

-Ben Ferraiuolo

**Comment by dnorgaard-usgs** [comment]
Hi Ben.  I am revisiting some older issues.  Regarding #1 and #2, it is possible to separate the log power and min/max freq options for spectra and spectrogram.  Our seismologists here so far has not found it a big enough nuisance though to address.  I'm also not sure if others would prefer to leave them the same so they don't have to modify these setting in two places.  Regardless, I opened a new ticket for this (#268).  

For #3, have you tried the 'Force Center' helicorder option?  From user manual:
_Force center forces each helicorder sample to be centered on its current line. This effectively eliminates all drift and is useful for broadband stations with lots of low frequency energy. This feature is to be used with caution though: it can make an obviously false signal look like an earthquake._
This may help with with viewing of HHZ or BHZ channels.  The improved plot then can saved as image (to address #4).

For #5, I previously mentioned we are unable to accommodate all the various ways users may want to plot their data.   I understand you may be hesitant to use ObsPy, but it is great for creating your own custom work so it is still my suggestion to give it a try.

**Comment by washingtonmagma** [comment]
Hey there! Thank you for the reply. Actually, SWARM does have a "plot generator". I cannot believe I actually missed it! It is called the wave clipboard. You can then take screenshots of the plots and it saves perfectly fine! It is actually is much better than what I was doing before. Thank you again for your help! Have a great day.
Sincerely,Ben Ferraiuolohttps://monitorseis.weebly.com

    On Tuesday, May 14, 2019, 3:38:32 PM PDT, Diana Norgaard <notifications@github.com> wrote:  
 
 
Hi Ben. I am revisiting some older issues. Regarding #1 and #2, it is possible to separate the log power and min/max freq options for spectra and spectrogram. Our seismologists here so far has not found it a big enough nuisance though to address. I'm also not sure if others would prefer to leave them the same so they don't have to modify these setting in two places. Regardless, I opened a new ticket for this (#268).

For #3, have you tried the 'Force Center' helicorder option? From user manual:
Force center forces each helicorder sample to be centered on its current line. This effectively eliminates all drift and is useful for broadband stations with lots of low frequency energy. This feature is to be used with caution though: it can make an obviously false signal look like an earthquake.
This may help with with viewing of HHZ or BHZ channels. The improved plot then can saved as image (to address #4).

For #5, I previously mentioned we are unable to accommodate all the various ways users may want to plot their data. I understand you may be hesitant to use ObsPy, but it is great for creating your own custom work so it is still my suggestion to give it a try.

**Comment by dnorgaard-usgs** [comment]
@washingtonmagma the changes for spectra/spectrogram options will go into 2.8.10 when released.

**Comment by washingtonmagma** [comment]
Woah, very cool! Thank you! I didn't think it would happen, but that is pretty cool. Thank you for all you do! SWARM is pretty damn cool.

Sincerely,Ben Ferraiuolohttps://monitorseis.weebly.com
 

    On Thursday, May 23, 2019, 4:03:50 PM PDT, Diana Norgaard <notifications@github.com> wrote:  
 
 
@washingtonmagma the changes for spectra/spectrogram options will go into 2.8.10 when released.
