### ISSUE TITLE
Start kiosk mode using a saved layout

### ISSUE THREAD

**Issue by iannesbitt** [usgs/swarm#252]
This is a feature request for the ability to load a saved layout into kiosk mode at start.

I can load sources to kiosk mode just fine at startup, and alternatively I can load a saved layout in the standard display window, but there doesn't seem to be a way to load an entire saved layout to kiosk mode at startup. Or perhaps I'm overlooking some functionality?

Thank you in advance.

**Comment by dnorgaard-usgs** [comment]
Hi.  Try adding the following to your layout's config file:

kiosk=true

Alternatively, you can save your layout in Kiosk mode using Ctrl-L, which will save this entry in the layout config for you.  Let me know if this solves your problem or not.

**Comment by iannesbitt** [comment]
Hi Diana,

This works on one machine and not on another, so I'll keep playing with the config settings on the other to get it working. Thank you for your help.
