### ISSUE TITLE
Acquiring data from TC1 seismometer

### ISSUE THREAD

**Issue by kbouk** [usgs/swarm#260]
Dear all,

We are using TC1 seismometers in a school network that we have connected to SeisComP3 using a modifed minilogger_plugin and acquiring them real-time through Seedlink. The sampling rate is at 18.8 sps. While SeisGram2K and JamaSeis read the data correct, Swarm seems to read the streams at 18.0 sps and the waveforms show gaps. Is there a way to resolve this. The daily miniseed files produced in SeisComP3 have no gaps.

Thank you and best regards,

Kostas Boukouras
Insitutute of Geodynamics
National Observatory of Athens
Athens-Greece

**Comment by MAKISCH** [comment]
![sampling](https://user-images.githubusercontent.com/49476802/55866185-7b127d80-5b88-11e9-8906-2d433f057e80.png)

**Comment by pdtdenton** [comment]
is this an encoding issue ?   the TC1 seedlink stream is encoded as 16bit integer, I have a feeling that some software automatically assumes that all SEEDLINK streams are steim2 encoded ?

**Comment by gchoul** [comment]
![SWARM vs SEISGRAM2k](https://user-images.githubusercontent.com/49476802/55870028-62a66100-5b90-11e9-9bef-c5305a0a8b42.png)

**Comment by dnorgaard-usgs** [comment]
Can someone point me to a SeedLink data source I can connect to and give me an example of a channel with this issue so I can troubleshoot?

**Comment by kbouk** [comment]
Hello,

You can connect at 194.177.194.254:18000
Station Name: SNOA
Network: HL
Stream: BHZ
Location Code: 01
The data are coming from a TC1 seismometer, sampled at 18.78 sps.

Best regards,

Kostas

**Comment by dnorgaard-usgs** [comment]
It is decoding as 16 bit integer with the correct sample rate.  The status text was rounding the sample rate to integer for some reason.  Unsure yet why the gaps though.

**Comment by dnorgaard-usgs** [comment]
It appears to me that all the gaps are about 12 seconds long, which is about ~228 samples, which is about what is getting sent per packet.  The occurrence seems random too.  Perhaps packet loss?  Though not sure why this would be a problem with this channel and not others.  I'll keep digging.

**Comment by gchoul** [comment]
great news your assistance, we deeply appreciated, 
best from Athens, 
Makis Chouliaras

..........................................
Dr. Gerasimos Chouliaras 
Geophysicist / Seismologist
Research Director 
Institute of Geodynamics 
National Observatory of Athens 
Lofos Nymfon, Thision, 
11810 Athens, Greece
.........................................
Cell : (+30)6944520440
E-mail: g.choul@noa.gr 
Skype : chouliaras.gerasimos
Web: -http://members.noa.gr/g.choul/en/home.html 
             -http://bbnet.gein.noa.gr/ol3/ol3_sn.html
             -http://sse-project.eu/
...........................................

**Comment by dnorgaard-usgs** [comment]
Fix made in volcano-core: https://github.com/usgs/volcano-core/pull/85/commits/69b143be23a05376eb1a73dc2cd90fedf41cd8eb

**Comment by dnorgaard-usgs** [comment]
Hi @kbouk @gchoul. I believe I have a fix for the gap issue and it is committed to master branch.  Are you able to build Swarm from GitHub or do you want me to build it and send you an updated snapshot version to test?

**Comment by gchoul** [comment]
Great news to wake up to, we will test and reply to you this morning, many thanks, Makis 

..........................................
Dr. Gerasimos Chouliaras 
Geophysicist / Seismologist
Research Director 
Institute of Geodynamics 
National Observatory of Athens 
Lofos Nymfon, Thision, 
11810 Athens, Greece
.........................................
Cell : (+30)6944520440
E-mail: g.choul@noa.gr 
Skype : chouliaras.gerasimos
Web: -http://members.noa.gr/g.choul/en/home.html 
             -http://bbnet.gein.noa.gr/ol3/ol3_sn.html
             -http://sse-project.eu/
...........................................

**Comment by kbouk** [comment]
Dear Diana,

Sorry for the late response, i just returned from Easter vacations. Could
you advice on how to build swarm from Github ?

Thank you and best regards,

Kostas Boukouras

**Comment by dnorgaard-usgs** [comment]
[swarm-2.8.10-SNAPSHOT-bin.zip](https://github.com/usgs/swarm/files/3174852/swarm-2.8.10-SNAPSHOT-bin.zip)

Hi.  Sorry for delay in response.  I've attached a snapshot of 2.8.10 with the fix here.  Please let me know how it goes.

**Comment by dnorgaard-usgs** [comment]
@kbouk @gchoul  Hello.  I am hoping to release 2.8.10 soon but would like to get confirmation that your issue is fixed. Just thought I'd follow up in case you didn't see my previous comment with the compiled snapshot.  Thanks.

**Comment by kbouk** [comment]
Dear Diana,

Sorry for the late response, we are again in a workshop in Cyprus.
I downloaded and tested the snapshot and acquires data from TC1 seismometer
using the seiscomp3 minilogger plugin without any problem or gap now.
Thank you very much for your time and work.

Best regards,

Kostas Boukouras

**Comment by dnorgaard-usgs** [comment]
Great!  The change will go into 2.8.10 when released.

**Comment by gchoul** [comment]
I thank you very much for your aid and solution, 

 

Best wishes from Athens, 

Makis 

 

..........................................

Dr. Gerasimos Chouliaras 

Geophysicist / Seismologist

Research Director 

Institute of Geodynamics 

National Observatory of Athens 

Lofos Nymfon, Thision, 

11810 Athens, Greece

.........................................

Cell : (+30)6944520440

E-mail:  <mailto:g.choul@noa.gr> g.choul@noa.gr 

Skype : chouliaras.gerasimos

Web: - <http://members.noa.gr/g.choul/en/home.html> http://members.noa.gr/g.choul/en/home.html 

           - <http://bbnet.gein.noa.gr/ol3/ol3_sn.html> http://bbnet.gein.noa.gr/ol3/ol3_sn.html

           - <http://sse-project.eu/?m=2> http://sse-project.eu/

...........................................

 

 

This email communication, including all attachments, may contain private, proprietary, privileged and/or confidential information and is intended only for the person to whom it is addressed. Any unauthorized use, copying or distributing of the contents of this email is strictly prohibited. If you are not the intended recipient of this email,  and have received it in error, please delete it and notify the sender immediately.
