### ISSUE TITLE
Colorblind-friendly spectrogram

### ISSUE THREAD

**Issue by iannesbitt** [usgs/swarm#275]
Hello,

I have a suggestion which would not only help colorblind users interpret spectrograms in SWARM, it would also help those of us who can see the full spectrum. SWARM's spectrogram uses a rainbow color scale, which is ineffective at conveying numeric information properly, and virtually impossible to read for most colorblind users. @kwinkunks shared this image of a colorized LiDAR elevation dataset [on Twitter](https://twitter.com/kwinkunks/status/1121844842932449282) not long ago, which is a good demonstration of how rainbow colormaps distort our visual perception of data:
![image](https://user-images.githubusercontent.com/18689918/58981922-5eb64a00-87a1-11e9-8700-07dbe0d8ecf0.png)
Both colorblind and non-colorblind viewers will notice that the two right-hand color scales are more difficult to interpret in the blue and green bands, while those on the left convey stunning detail of abandoned river meanders in those same areas. This is because, in essence, the brightness of the image does not vary co-linearly with hue, and human eyes are much more attuned to perceive dark/light differences than differences in hue.

In light of this, I propose changing SWARM's spectrogram color scale to something perceptually uniform and linear. You can [read about perceptual uniformity/linearity here](https://bids.github.io/colormap/). At this link there are also public domain (Creative Commons 0—i.e. "no rights reserved") colormaps available in several languages, which I think can be ported to Java fairly easily.

**Comment by iannesbitt** [comment]
I see now that this is an upstream issue from https://github.com/usgs/volcano-core/tree/master/src/main/java/gov/usgs/volcanoes/core/legacy/plot/color. I will repost this issue in https://github.com/usgs/volcano-core.

**Comment by dnorgaard-usgs** [comment]
Added Inferno color map to volcano-core based on user suggestion in https://github.com/usgs/volcano-core/issues/90.  Will add option to allow user to use alternate spectrum in Wave Settings. i.e.:

![image](https://user-images.githubusercontent.com/25251719/64392392-70f28f00-d001-11e9-8faf-f1875e147488.png)

**Comment by dnorgaard-usgs** [comment]
You will also be able to make the new color spectrum default by changing

default.useAlternateSpectrum=false

to

default.useAlternateSpectrum=true

in WaveDefaults.config

**Comment by dnorgaard-usgs** [comment]
Will be available in 2.8.12 when released.

**Comment by iannesbitt** [comment]
Cheers. Thanks again.
