### ISSUE TITLE
Station Alias 

### ISSUE THREAD

**Issue by pdtdenton** [usgs/swarm#278]
I am trying to use the Alias function in SwarmMetadata.config 
eg 
R2303 EHZ AM 00= Alias:Swansea;Group:SKY

I can get stations assigned to different groups (in this case SKY ) but nothing I do wth teh Alias tag seems to make any difference .  Does anyone have an example i can see for   format 

thanks 
paul denton

**Comment by christian-phivolcs** [comment]
Hi Paul,
I think the alias will take effect when you're in kiosk mode. Please see attached screenshot and sample below.
RF979 HDF AM 00= Alias: VMAN RBOOM ; Longitude: 123.67389; Latitude: 13.23;  
RBFED HDF AM 00= Alias: VMRH RBOOM; Longitude: 123.67111; Latitude: 13.28333; 
RD5CF HDF AM 00= Alias: VMSM RBOOM; Longitude: 123.73; Latitude: 13.25194; 
RB56B HDF AM 00= Alias: VMLH RBOOM; Longitude: 123.7281; Latitude: 13.1598; 

Hope this helps.

cj
Sa taong may hiya, salita'y panunumpa.    -Emilio Jacinto (Mga Aral ng Katipunan sa Kartilya)  

    On Thursday, August 8, 2019, 9:08:15 PM GMT+8, Paul Denton <notifications@github.com> wrote:  
 
 
I am trying to use the Alias function in SwarmMetadata.config
eg
R2303 EHZ AM 00= Alias:Swansea;Group:SKY

I can get stations assigned to different groups (in this case SKY ) but nothing I do wth teh Alias tag seems to make any difference . Does anyone have an example i can see for format

thanks
paul denton

**Comment by gchoul** [comment]
Hi Paul here are my Swarm Metadata.config settings for the TC1 and Raspberryshake seedlinks :

 

SISM BHZ HL 01= Unit: nm/s;Longitude:27.124000;Latitude:38.264000;Group:HL ## (TC1 )Izmir,Turkey

Raspberryshake 

R4EB6 EHZ AM 00= Unit: nm/s;Longitude:23.717412;Latitude:37.972796;Group:AM ## Athens

 

..........................................

Dr. Gerasimos Chouliaras 

Geophysicist / Seismologist

Research Director 

Institute of Geodynamics 

National Observatory of Athens 

Lofos Nymfon, Thision, 

11810 Athens, Greece

.........................................

Cell : (+30)6944520440

E-mail:  <mailto:g.choul@noa.gr> g.choul@noa.gr 

Skype : chouliaras.gerasimos

Web: - <http://members.noa.gr/g.choul/en/home.html> http://members.noa.gr/g.choul/en/home.html 

           - <https://snac.gein.noa.gr/project-network/> https://snac.gein.noa.gr/project-network/

...........................................

 

 

This email communication, including all attachments, may contain private, proprietary, privileged and/or confidential information and is intended only for the person to whom it is addressed. Any unauthorized use, copying or distributing of the contents of this email is strictly prohibited. If you are not the intended recipient of this email,  and have received it in error, please delete it and notify the sender immediately.

**Comment by pdtdenton** [comment]
thanks for the help 
I can see now that the Alias option works on the helicorder display in Kiosk mode.    I had been using the kiosk mode with wave monitor display because i wanted to be able to display live filtered data.  

It would be nice if the alias worked across different display options (ditto for local time zones which only aply to helicorder displays also.)

**Comment by dnorgaard-usgs** [comment]
@pdtdenton Right now alias is only displayed on helicorders in kiosk mode.  We generally try to avoid changing default behaviors since folks get accustomed to it and may not welcome changes.  However, I can understand the frustration of the inconsistency in how alias works, especially since the documentation hadn't clarified this.  I'm considering supporting alias in the multimonitor window.  Is there anywhere else this would be important to you?

**Comment by dnorgaard-usgs** [comment]
alias will be supported in Monitor
