### ISSUE TITLE
Provide different color map options for spectrograms

### ISSUE THREAD

**Issue by rumachan** [usgs/swarm#285]
It looks like Swarm uses a rainbow or jet color map (I think they are the same?) for it's spectrograms. As far as I am aware the color map is not selectable; only one map is provided. It would be helpful to provide a few additional color maps for the user to chose from. And maybe even change the default.

Rainbow/jet is widely known to not be perceptually uniform, which can add artificial highlights to your spectrogram.

Suggested additional color maps are (in the python world) viridis, plasma, magma, inferno, cividis.

Thanks.

**Comment by iannesbitt** [comment]
This was addressed in #275 and I believe commits have been put in place to allow user selection of either Inferno or Jet.

**Comment by rumachan** [comment]
Thanks, great minds think alike!

**Comment by iannesbitt** [comment]
Cheers, I'm glad others are also advocating for perceptual linearity!
