### ISSUE TITLE
VP/Vs in Hypo71

### ISSUE THREAD

**Issue by alebrovelli** [usgs/swarm#287]
Dear Diana,
from a few tests I made, I realized that hypo71 uses the same Vp/Vs in all runs (default value 1.78, "POS" variable, 5th entry in the ControlCard array), regardless of what is set in the swarm config file.
I think this value should be instead taken from the "velocityRatio" setting in Swarm.config.

Kind regards
Alessandro Brovelli

**Comment by alebrovelli** [comment]
I found another bug, somehow related to the one above. I am pretty sure the s-pick times are not correctly "sent" to hypo71. In the output of hypo71 I find values that are different from the one picked manually. The p-picks instead are correct.
Let me know if/how I can help fixing these bugs, which are quite critical, as they result in wrong localizations.

A side note: I made a comparison between the standalone Hypo71PC and the version that comes with swarm, and after manually correcting the s-times the results are consistent.

Thank you
regards
Alessandro

**Comment by dnorgaard-usgs** [comment]
I have added below prior to the hypo71.calculateHypo71 step in Hypo71Manager.calculate:
      controlCard.setPOS(SwarmConfig.getInstance().velocityRatio);

**Comment by dnorgaard-usgs** [comment]
With regards to the S-arrival time, perhaps I misinterpreted the Hypo71 documentation on this:

![image](https://user-images.githubusercontent.com/25251719/65997782-df830b00-e44e-11e9-88f8-50a08386c68a.png)

My original interpretation was I could not just take the S-arrival seconds in case it crossed into the next minute, so I took  (P-arrival seconds)+(P-arrival time - S-arrival time in seconds).  Re-reading the "**" note above, it sounds to me like I need to apply 60 seconds to SEC and S if the S-arrival crosses the minute, but it is not clear to me.  What is your interpretation?

**Comment by dnorgaard-usgs** [comment]
2.8.13 is out with the Vp/Vs change for Hypo71 (plus a fix for bug introduced in 2.8.12).  I will await for your comments before addressing the second issue you mention.  Actually, if you can make a second ticket for it that would be great.  This way we can close this one for the Vp/Vs.

**Comment by alebrovelli** [comment]
ok! thank you Diana
