### ISSUE TITLE
Improve loading of wave clipboard upon QuakeML import

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#293]
The current method of searching for potential data sources applicable to a pick is inefficient.  Improvements can be made by storing previously found data source and trying it first.  Also, instead of searching for channel in list code can attempt to get wave from the data source and if valid wave data is found then use it.

**Comment by gchoul** [comment]
i’m simply amazed, thank you !

..........................................
Dr. Gerasimos Chouliaras 
Geophysicist / Seismologist
Research Director 
Institute of Geodynamics 
National Observatory of Athens 
Lofos Nymfon, Thision, 
11810 Athens, Greece
.........................................
Cell : (+30)6944520440
E-mail: g.choul@noa.gr 
Skype : chouliaras.gerasimos
Web: -http://members.noa.gr/g.choul/en/home.html 
             -http://snac.gein.noa.gr/project-network/
             -http://sse-project.eu/
...........................................

**Comment by alebrovelli** [comment]
yes, that would be great!

**Comment by dnorgaard-usgs** [comment]
This went out in 3.0
