### ISSUE TITLE
Opened files are rejected

### ISSUE THREAD

**Issue by iannesbitt** [usgs/swarm#301]
A user reports issues using the "Open File..." dialog in 2.8.13. I have confirmed the issue exists for me as well, in both 2.8.12 and 2.8.13. To replicate: try to open a file (mseed, sac, etc) using File > Open File. No error is thrown in the console but the files do not load as expected.

For reference, the files load properly in Obspy and PQLX/SQLX, and in 2.8.8.

![image](https://user-images.githubusercontent.com/18689918/67595759-f1458e80-f72c-11e9-865f-5bf9a67f199a.png)
![image](https://user-images.githubusercontent.com/18689918/67595852-28b43b00-f72d-11e9-9432-661e5899a9d7.png)
![image](https://user-images.githubusercontent.com/18689918/67596623-c78d6700-f72e-11e9-9ec7-7e730c3d11c8.png)
![image](https://user-images.githubusercontent.com/18689918/67596662-dffd8180-f72e-11e9-8a33-3b23b5cba46d.png)

**Comment by dnorgaard-usgs** [comment]
I am able to open sample files I have.  Can you attach the file you are having trouble opening?

**Comment by iannesbitt** [comment]
Interesting. Well, here is a zip of the example file I showed:
[AM.R3BCF.00.EHZ.D.2019.297.zip](https://github.com/usgs/swarm/files/3860591/AM.R3BCF.00.EHZ.D.2019.297.zip)

**Comment by dnorgaard-usgs** [comment]
I was able to open the file.  To be sure, I used to 2.8.13:

![image](https://user-images.githubusercontent.com/25251719/69095204-b0c4f200-0a06-11ea-82fa-955af271dc89.png)

What operating system are you on?

**Comment by iannesbitt** [comment]
I am on Ubuntu 19.04, but the user is on Windows 10. Very strange.

**Comment by iannesbitt** [comment]
Actually, I think the user is on Windows 8. I will clarify.

**Comment by dnorgaard-usgs** [comment]
I am on Windows 10.  Also checked it works on MacOS 10.14.6.

**Comment by dnorgaard-usgs** [comment]
Hi.  Any update?

**Comment by iannesbitt** [comment]
I have not received word from the user. I can now open files when I create a new `Swarm.config` and copy sources from the old config, so I am closing the issue.
