### ISSUE TITLE
my network station on map

### ISSUE THREAD

**Issue by dsandron** [usgs/swarm#303]
Hello,
I added my SeedLink Server and I can see the data.
I'm not able to see my stations on map.
I tried, without success, with SwarmMetadata.config file.
Years ago I was able to do it. 
I downloaded 2..8.13 version.
Please, someone can help me?

Denis

**Comment by dnorgaard-usgs** [comment]
You need to add the station locations to SwarmMetadata.config since Swarm does not get this info from the SeedLink server.  Please see user manual for details.

**Comment by gchoul** [comment]
It would be more user friendly for SWARM to get this information from the seedlink server and also from the headers of sac miniseed etc files when loaded, sincerely yours, Makis

..........................................
Dr. Gerasimos Chouliaras 
Geophysicist / Seismologist
Research Director 
Institute of Geodynamics 
National Observatory of Athens 
Lofos Nymfon, Thision, 
11810 Athens, Greece
.........................................
Cell : (+30)6944520440
E-mail: g.choul@noa.gr 
Skype : chouliaras.gerasimos
Web: -http://members.noa.gr/g.choul/en/home.html 
            -http://snac.gein.noa.gr/project-network/
...........................................
