### ISSUE TITLE
Meters per second is shown as zero if min/max is below 0.000001

### ISSUE THREAD

**Issue by iannesbitt** [usgs/swarm#306]
With calibrations turned on, stations that have vibration below 1*10^(-6) m/s have tick labels of 0 and -0 in seismogram view. This seems to occur only for labels below 0.000001. (see example images)

![image](https://user-images.githubusercontent.com/18689918/72746248-9ed70b00-3b7f-11ea-8733-5122b6748df6.png)
![image](https://user-images.githubusercontent.com/18689918/72747408-8d433280-3b82-11ea-9bdf-9eda59da8aa3.png)

**Comment by dnorgaard-usgs** [comment]
Hi.  Can you please export and attache here a snippet of your data so that I can use it to test it once fixed?  Thanks.

**Comment by dnorgaard-usgs** [comment]
Actually it would be useful for troubleshooting also.

**Comment by iannesbitt** [comment]
Here is 20 minutes' worth of data from two different stations, both of which have quiet-enough periods that I can reproduce the issue by zooming in.

[AM.RCB43.00.SHZ.D.2020.024.mseed.zip](https://github.com/usgs/swarm/files/4110217/AM.RCB43.00.SHZ.D.2020.024.mseed.zip)
[AM.R24FA.00.EHZ.D.2020.021.mseed.zip](https://github.com/usgs/swarm/files/4110178/AM.R24FA.00.EHZ.D.2020.021.mseed.zip)

**Comment by dnorgaard-usgs** [comment]
I'm having difficulty zooming in enough to reproduce.  Can you post a screenshot of your wave settings?

**Comment by iannesbitt** [comment]
Thinking about it a bit more, the problem may be that you don't have calibrations for these data. Can you connect to the Raspberry Shake WWS directly at caps.raspberryshake.net:16022? That's the easiest way I can think of reproducing it. Station RCB43.SHZ has consistently quiet data.

Anyway, my wave settings:
![image](https://user-images.githubusercontent.com/18689918/73106813-4f1f7900-3eca-11ea-86be-67680092dcda.png)

**Comment by dnorgaard-usgs** [comment]
I could not connect to it.  Not having much luck reproducing with other data sources either. I'll keep looking around for other sources.

**Comment by iannesbitt** [comment]
Sorry that should be caps.raspberryshake.**com**:16022

**Comment by dnorgaard-usgs** [comment]
Doesn't seem to like me connecting to it:

java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by iannesbitt** [comment]
I've never seen this before, and can't reproduce it when connecting from devices both in the US and Panama. I will report it to our developers. Did you get this error immediately upon connecting or after a delay?

**Comment by dnorgaard-usgs** [comment]
Perhaps a couple second delay.

**Comment by dnorgaard-usgs** [comment]
I was able to connect with caps.raspberryshakedata.com.

**Comment by iannesbitt** [comment]
Ok, good to hear. Your connection is not being forcibly closed anymore?

**Comment by dnorgaard-usgs** [comment]
![clipboard](https://user-images.githubusercontent.com/25251719/73407716-ddbb3e00-42ae-11ea-8ff5-09ca27f6c46f.png)

How's this?

**Comment by dnorgaard-usgs** [comment]
Fix in 3.0.1 

https://volcanoes.usgs.gov/software/swarm/download.shtml

**Comment by iannesbitt** [comment]
This is perfect, thank you once again Diana.
