### ISSUE TITLE
FDSN without records

### ISSUE THREAD

**Issue by Thor0001** [usgs/swarm#316]
New  v3.1.0 working ok, only one error apparently from IRIS, since Feb14 not connect & no Helicorder records  FDSN / St NNA ; any suggest?, thanks.

**Comment by dnorgaard-usgs** [comment]
What network?  Is it a 3.1.0 issue or Iris FDSN just not working?

**Comment by Thor0001** [comment]
v3.1.0 working ok, one problem just w/Network II - St NNA (w/FDSN conection).

**Comment by dnorgaard-usgs** [comment]
This does not appear to be a Swarm issue so I am closing.
