### ISSUE TITLE
stream chain AND info type are empty & problems with the connection description.

### ISSUE THREAD

**Issue by GaiaCode-Rob** [usgs/swarm#318]
Hello wonderful people,

First of all i would like to apologise as i am new to Git Hub so in all probability I'm using this system incorrectly! 

I work for a new company called Gaia Code and we are implementing the SeedLink data transmission protocol but we have run into some issues and are finding it hard progress.

After ~5 minutes of our system running on swarm we get the following error messages: 

ERROR: [xxx.xxx.xxx.xxx:18000] stream chain AND info type are empty
ERROR: [xxx.xxx.xxx.xxx:18000] problems with the connection description

We would love to know why we get these messages and how to stop them! 

We are also getting gaps in the data when backfill gets to ~24Hrs, we are not sure if this is related to these error messages. If we look at the data packets with a network analysis tool we can see the data being sent to SWARM when we see gaps in the helicorder. 

If anybody can be of any assistance we will be forever thankful.

Kind Regards,

Robert Aikman

Gaia Code 

![SEED ERROR GAPS](https://user-images.githubusercontent.com/63452773/78989060-6e718e00-7b2a-11ea-8e7f-b00f26589988.png)
![SEED ERROR MESSAGE](https://user-images.githubusercontent.com/63452773/78989063-703b5180-7b2a-11ea-86d8-26fe465c94dc.png)

**Comment by dnorgaard-usgs** [comment]
I got that error once, but it did not seem to affect data from coming in.  My helicorders are still populating data.  It sounds like you get it frequently though?  

I will keep it running over night to see if I get the gaps you mention.

**Comment by GaiaCode-Rob** [comment]
Hi Diana, 
Thank you very much for your reply.
The plot thickens! We were hoping this error message was the source of all our swarm issues! 

We have since found that changing the default Helicorder View Settings mainly the refresh time from the default 15 sec to 120 sec we get much better performance and most of the gaps fill.  

![Helicorder View Settings](https://user-images.githubusercontent.com/63452773/79854403-4c48fd00-83c1-11ea-8e9d-4ee5deebc96b.png)
![Helicorder Gaps](https://user-images.githubusercontent.com/63452773/79854434-57039200-83c1-11ea-9b13-05bbc150156d.png)
![Helicorder Gaps after refresh time adjust](https://user-images.githubusercontent.com/63452773/79854459-5f5bcd00-83c1-11ea-83a9-45de81988c41.png)

**Comment by dnorgaard-usgs** [comment]
Does this mean your issue is resolved?

**Comment by garygonzales** [comment]
I have mine set for 1 second Refresh time, and I don't have that problem.

**Comment by dnorgaard-usgs** [comment]
Assuming issue is resolved for original poster.  Closing.
