### ISSUE TITLE
Raspberry Pi ???

### ISSUE THREAD

**Issue by TCP491016** [usgs/swarm#321]
I have tried to follow the Linux Instructions for installing Swarm on my R-PI-3. It almost works, but not quite. Are there special instructions for this? Does the Swarm folder need to go into a particular directory? Are there any other packages that need to be downloaded as well?

**Comment by dnorgaard-usgs** [comment]
Hi.  We don't provide special support for Raspberry Shake, but here is an article that describes how to use Swarm with it:

https://magpi.raspberrypi.org/articles/use-swarm-with-raspberry-shake-seismographic-data

And from RaspberryShake site:

https://manual.raspberryshake.org/swarm.html

If you are still having issues, I would suggest contacting someone in the Raspberry Shake community.

**Comment by TCP491016** [comment]
Never mind. I solved my own problem.  Seems like my JAVA was pointed to the OpenJDK version rather than the Oracle version. Works fine now.
