### ISSUE TITLE
Non continuous helicoders

### ISSUE THREAD

**Issue by danruba** [usgs/swarm#322]
After some hours the helicorders are no longer continuous, what setup should I to modify?

![image](https://user-images.githubusercontent.com/68612460/88094222-d8052d80-cb58-11ea-9e99-2dc5b429a23d.png)

**Comment by christian-phivolcs** [comment]
Hi,
Increasing the memory allocation for Java will do the trick. Edit swarm.sh or swarm_console.bat, i.e. allocate 1024mb of RAM. Right after the word java, type:     -Xmx1024m
Hope this helps.
Cheers,cj

Sa taong may hiya, salita'y panunumpa.    -Emilio Jacinto (Mga Aral ng Katipunan sa Kartilya)  

    On Wednesday, July 22, 2020, 2:51:08 AM GMT+8, danruba <notifications@github.com> wrote:  
 
 


After some hours the helicorders are no longer continuous, what setup should I to modify?

**Comment by danruba** [comment]
Thanks a lot, all looks great
