### ISSUE TITLE
Helicorder not showing new data with FDSN data source

### ISSUE THREAD

**Issue by rumachan** [usgs/swarm#323]
We have noticed that with our FDSN data source that helicorders are not showing new data. When a user opens the helicorder, the data all display, but as time progresses the new data (that since the helicorder was opened) does not show. However, if the user clicks in the 'empty' part of the helicorder, the zoom window shows data.
![Screenshot from 2020-07-23 15-54-45](https://user-images.githubusercontent.com/10933207/88250885-18051580-ccfd-11ea-8b8d-a0ab60dd9d05.png)

This behaviour has been noted by users using both Windows and Linux OSs. I have copies of most versions back to 2.8.3 and have observed that the problem does not occur until version 2.8.7. In the following you can see that ver 2.8.3 and 2.8.6 have helicorders that are updating, but all versions since 2.8.7 have the problem described.
![Screenshot from 2020-07-23 15-45-24](https://user-images.githubusercontent.com/10933207/88250992-7f22ca00-ccfd-11ea-9133-00fbda176fde.png)
Our FDSN data source in this situation is http://service-nrt.geonet.org.nz/fdsnws/dataselect/1/query for Dataselect and http://service-nrt.geonet.org.nz/fdsnws/station/1/query for Station. This is an open FDSN server you you can try to reproduce this problem.
I wonder if the fix for this bug https://github.com/usgs/swarm/issues/182, which coincidentally for was for me, has introduced this problem?
Thank you.

**Comment by himmetgencer** [comment]
Hi, 

The same issue continues when using seedlink server as datasource. Also old data is not loaded, after some hours stream stop.

Swarm version : 3.0.1
Operating system: Windows 10

Thanks... 

![IMG_20200725_135904](https://user-images.githubusercontent.com/6142011/88455607-57f40600-ce7f-11ea-9a91-b3eb157c62cf.jpg)

**Comment by dnorgaard-usgs** [comment]
@rumachan You are correct... it appears reverting that change fixes this issue.  I'm attaching a version with that change reverted so you can confirm.  Or do you get the heap error again?

[swarm-3.2.0-snapshot-bin.zip](https://github.com/usgs/swarm/files/4985130/swarm-3.2.0-snapshot-bin.zip)

**Comment by dnorgaard-usgs** [comment]
@himmetgencer Please open a separate ticket for SeedLink issue.

**Comment by rumachan** [comment]
@dnorgaard-usgs Thank you for looking at this. With 3.2.0-snapshot I see regular updating of the helicorder - excellent.
![swarm_3 2 0_updating](https://user-images.githubusercontent.com/10933207/88623968-36528300-d0fa-11ea-9971-559748d7df83.png)
For 'old' data, which was where the heap error occurred, I have to use the FDSN server specifically for old data. I displayed helicorders for a range of sites/dates and never once got a heap error - excellent, but difficult to understand.
What I am seeing, but I think this is completely unrelated are numerous message such as `2020-07-28 05:48:30  WARN - could not get web service raw data (OTVZ HHZ NZ 10): Did not get an OK repsonse code (code=413, url=http://service.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=OTVZ&loc=10&cha=HHZ&start=2017-01-02T00:28:59&end=2020-07-28T05:48:30"`.

**Comment by himmetgencer** [comment]
> @himmetgencer Please open a separate ticket for SeedLink issue.

Thanks for answer, I've created new ticket for seedlink issue.

Have a nice day...

**Comment by dnorgaard-usgs** [comment]
@rumachan Ok, I will revert that one change and put it into next release.  As for the warning, my thought is that the channel it referenced was not available for some reason.  It seems to be fine at the moment (no warning, data coming in for OTVZ HHZ)

**Comment by rumachan** [comment]
Thank you @dnorgaard-usgs
