### ISSUE TITLE
Stream stopping and not showing old data Seedlink Server as datasource

### ISSUE THREAD

**Issue by himmetgencer** [usgs/swarm#324]
Hi,

I am using swarm 3.1.0 and 3.2.0-snapshot with  a seedlink server as datasource. After some hours/minutes stream stop and old data is not loaded. Also when the user clicks in the empty part of helicorder, the zoom windows shows data.

I tested it with option -Xmx1024m, but this issue continues. Also I'm using SeisGram2K and jAmaseis software, everything is correct.

![image](https://user-images.githubusercontent.com/6142011/88626906-19935c80-d0b4-11ea-84a3-281fcdf04c0d.png)

OS: Windows-10 64-Bit
Swarm version: 3.1.0 - 3.2.0-snapshot

Regards...

**Comment by dnorgaard-usgs** [comment]
About how many hours will it run before it stops updating?  I am trying to reproduce this.

**Comment by himmetgencer** [comment]
Hi, thanks for answer,

Sometimes 4-5 hour, sometimes after 12-13 hours. it's actually random. Also old data is not loaded.

Also you can find screenshot of jAmaseis software.

![image](https://user-images.githubusercontent.com/6142011/88707824-76762d80-d11b-11ea-9bcb-077fdb409ec9.png)

**Comment by dnorgaard-usgs** [comment]
[swarm-3.2.0-snapshot-bin.zip](https://github.com/usgs/swarm/files/5008967/swarm-3.2.0-snapshot-bin.zip)

I haven't been able to reproduce the problem with the stream stopping, but I made some changes that may or may not help.  Can you try the attached?  I also made some improvements for getting past data, though I need to work on it some more.

**Comment by himmetgencer** [comment]
Thank you, I will try it and I will send results.

Regards...

**Comment by himmetgencer** [comment]
Hi again,

I've tried version 3.2.0 . But stream stopped after 30 minutes. But jAmaseis software continues collect data. Also past data is not loaded.

Regards... 

Windows 10 64-Bit
Swarm 3.2.0
200 sps x 3 axes accelerometer (STEIM1) 

![Screenshot_2020-08-01-12-17-14-549_com anydesk anydeskandroid](https://user-images.githubusercontent.com/6142011/89098710-a3b02d80-d3f2-11ea-910e-53595296b124.png)

**Comment by himmetgencer** [comment]
Also, I'm uploading another screenshot of swarm console. 

![Screenshot_2020-08-01-12-56-06-021_com anydesk anydeskandroid](https://user-images.githubusercontent.com/6142011/89099362-4e2a4f80-d3f7-11ea-8118-15449cddcf05.png)

**Comment by dnorgaard-usgs** [comment]
Well, that's not good that it got worse :(  Can you see how much heap space is allocated?  Also what is your helicorder setting?  I don't suppose your SeedLink server is accessible to me to troubleshoot?  With the servers I have available I'm able to run helicorders for days without any stream break.

**Comment by himmetgencer** [comment]
Thanks for answer,

I sent seedlink server information to "dnorgaard@usgs.gov". I will keep it open for 48 hours because of company policy.

I'm using default helicorder settings. Only I run the software with "-Xmx1024m" option.

I'll send heap size is allocated.

Regards...

**Comment by himmetgencer** [comment]
You can see heap size in below screenshot.
Have you received information of seedlink server? 

Regards... 

![Screenshot_2020-08-02-12-55-36-995_com anydesk anydeskandroid](https://user-images.githubusercontent.com/6142011/89120565-07545c80-d4c0-11ea-83ca-514ccbd4a2bf.png)

**Comment by dnorgaard-usgs** [comment]
[swarm-3.2.0-snapshot-bin.zip](https://github.com/usgs/swarm/files/5031377/swarm-3.2.0-snapshot-bin.zip)

**Comment by himmetgencer** [comment]
Thanks for answer, I will try short term alternative features next week. But this issue needs to be resolved. 

Regards...

**Comment by dnorgaard-usgs** [comment]
My understanding is that SeedLink is a real-time data acquisition protocol and not necessarily the best source for historical waveform data.  Most SeedLink servers I have seen have less than 24 hours of buffer.  Since you do have a fairly large buffer, I tried to see what I could do, but I am not going to be able to allocate much more time to this issue.  There are ways to preserve the wave data for long-term storage that is more friendly for accessing historical data.  Winston wave server works particularly well with Swarm.  One option is to use Earthworm's slink2ew to import data into Swarm, and then to export it to Winston.  If you are not familiar with these software, I can point you to some documentation that may help.  You have my email address so please let me know if you would like this information.

**Comment by himmetgencer** [comment]
Please Can you send documentations to my email? Also I will reply to your comment next week.

Regards...
