### ISSUE TITLE
WIN files cannot be opened

### ISSUE THREAD

**Issue by martanto** [usgs/swarm#325]
Following the documentation, I need .config file to open WIN files. So I created the .config file, but it always return an error, file cannot be opened. I am using Swarm 3.1. Trying to open the files using Obspy, its working, and I can plot the data. Here is the file example:

[Sinabung.zip](https://github.com/usgs/swarm/files/5177971/Sinabung.zip)

edit: add Swarm version

**Comment by dnorgaard-usgs** [comment]
Hi, can you add the config file you created?

**Comment by dnorgaard-usgs** [comment]
I was able to open the file in Python as you say.  I will take a look at obspy code.

**Comment by dnorgaard-usgs** [comment]
Having trouble reading data after ac75, which has data size 0.  I think I am not reading data correctly for data size 0 and subsequently data is not read correctly.  I tried doing same as obspy but no luck.  Do you know where I can find specs for WIN file?  I'll keep looking in meantime.

**Comment by dnorgaard-usgs** [comment]
[swarm-3.2.0-snapshot-bin.zip](https://github.com/usgs/swarm/files/5192433/swarm-3.2.0-snapshot-bin.zip)

Please give the attached a try.  It is not an official release so please do not distribute too widely.  Also, it appears I am able to at least pull station info from file, though not the channel or network.  Do you think it is sufficient and that the config file is not needed?

**Comment by dnorgaard-usgs** [comment]
fixed for 3.2

**Comment by martanto** [comment]
Hai, I am really really sorry, I just read your comment. I dont know why there is no notification on my profile. Thank you for your help!
