### ISSUE TITLE
SEEDLINK data source is not working according to IRIS DMC

### ISSUE THREAD

**Issue by seismopaul** [usgs/swarm#45]
Chad wrote:

> As you likely remember IRIS funded the addition of SeedLink support in Swarm a few years ago.  I recently download the latest version of Swarm (2.5.9) to try it out.  Unfortunately it doesn't appear to function well, it kinda sorta looks like it's doing something but not what I would expect. 
> 
> Attached you can see a sequence of screen shots after I unzipped the 2.5.9 release, added rtserve.iris.washington.edu as the "IRIS SeedLink" source, selected MSTX BHZ TA as the channel and requested both a "Monitor" window and a "realtime" window.  I started the streams at 18:28 UTC (11:28 local), the screen shots have the local time in their file name.
> 
> It's a little hard to describe the observations: the "Monitor" window gets updates sporadically and does not show the complete data and the "realtime" window gets a more complete waveform but only what looks like the most recent data.  During this time I was watching the SeedLink feed for this channel, packets arrived as semi-regular intervals and were a contiguous time series.
> 
> Swarm also emitted "Could not synchronize with NTP server", "getCurrentTime(): giving up" messages; not sure if it's related.  Hopefully the host clock would be used if NTP synchronization with (hard coded?) NTP servers is not possible.
> 
> Something seems really broken with this functionality.  Can someone confirm that Swarm's SeedLink-as-a-source is not working?  

Kevin tested out the latest version and found it working however and was not able to reproduce the problem. Tom mentioned that he recently changed something in the latest version of the seedlink data source by upgrading the library so something else may have changed. Needs verification by a third party that this is not functioning as it should.

**Comment by tparker-usgs** [comment]
Cannot duplicate.
