### ISSUE TITLE
swarm.jar

### ISSUE THREAD

**Issue by comoglu** [usgs/swarm#61]
Installation cannot find swarm.jar. Should it be copied from earlier version? Or this file is missing here?

**Comment by tparker-usgs** [comment]
swarm.jar should be in the lib/ directory. I verified that it is present in the most recent version. 

I'm closing this ticket, I don't think there's a bug here. However, something is not working for you. Send me an email with the version of swarm you're using and where you got the package and I'll try to help.

**Comment by comoglu** [comment]
I mean in Github. There is no lib folder there. On the other hand, it's
present on release publish page.
Thanks,
Mustafa

Mustafa ÇOMOĞLU - Seismologist

BOUN KOERI/ B.Ü. KRDAE Bölgesel Deprem-Tsunami Izleme ve Değerlendirme
Merkezi

comoglu@boun.edu.tr  comoglu@gmail.com

t :+90216 5163269

**Comment by tparker-usgs** [comment]
The Github repository just has the source code. The source gets
compiled to produce the swarm.jar file.

**Comment by comoglu** [comment]
I understand that.
Thanks,
Sorry for inconvenience,
Regards,
Mustafa


Mustafa ÇOMOĞLU - Seismologist

BOUN KOERI/ B.Ü. KRDAE Bölgesel Deprem-Tsunami Izleme ve Değerlendirme
Merkezi

comoglu@boun.edu.tr  comoglu@gmail.com

t :+90216 5163269
