### ISSUE TITLE
time markers on monitor waves

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/swarm#78]
User requests that the monitor display time markers similar to other wave views, rather than just the start and end times.

**Comment by virusdunil** [comment]
Agree ;)

**Comment by dnorgaard-usgs** [comment]
It is possible that others may prefer that start and end times are clear in the monitor.  Also, adding a time in center may not be helpful as there is no center grid line.  We will not make this change at this time, but will reconsider in future if other observatory users responsible for monitoring volcanoes request it.
