### ISSUE TITLE
WMS HTTP URLs?

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/swarm#81]
Loren reports that WMS forces the use of HTTP URLs. HTTPS URLs should be supported.

**Comment by dnorgaard-usgs** [comment]
I'm not sure I fully understand the issue here, but https does appear supported.  The basemaps have moved to an https URL so I have updated NationalMapLayer class accordingly.  Working just fine for me with https urls.

**Comment by dnorgaard-usgs** [comment]
Not an issue to our knowledge. Closing.
