### ISSUE TITLE
Plot events on helicorder

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#92]
Jay W suggested plotting events on helicorder (perhaps as red dots, similar to how Columbians make helicorders).

**Comment by jwellik** [comment]
Here is an image of a smoke drum record from Columbia with manually placed dots to mark events. This is just an example of a place where this is done for display purposes.

![helicorder_columbia](https://cloud.githubusercontent.com/assets/20360217/25494551/ce007876-2b2e-11e7-8e49-1ada49c1781e.png)

**Comment by dnorgaard-usgs** [comment]
replaced by #199
